### PR TITLE
couple of advices

### PR DESCRIPTION
**Pull request by Extervin**
Made some comments to help you improve, if you still working on this project. Let me know if you want more

### CODE REVIEW

**Comment by Amiinaa08** [comment]
I'm very grateful for your advices!
I have only started studying it recently, and I don't know a lot of stuff yet. But I will definitely use it to improve myself a lot!
I will merge this pull request now.

**Comment by Amiinaa08** [comment]
@Extervin 
Moving the styles to the top was a mistake. As I have Bootstrap used on my website, it has to be loaded at first, and only then we need to apply our styles. 
If we load our custom styles at first, we wouldn't be able to overwrite the Bootstrap styles without using the `!important` flag ([stackoverflow article](https://stackoverflow.com/questions/26640250/using-bootstrap-and-my-own-css-together)).
So, I will move the styles back as they were before.

**Comment by Extervin** [comment]
My mistake, I was sleepy and mixed up the order of application of the rules in the CSS. Are you going to add any complex designs like animations in the future? Because I'd like to maintain my front-end skills while I'm working on another project, and it's much easier to do that by helping someone else.

**Comment by Amiinaa08** [comment]
This project was something like a beginner one, my first attempt to write HTML/CSS markup properly. There are some lightweight animations and a carousel, and I don't really know what to add there else.
I am going to learn JavaScript right now, and after this I would like to create a new app.
So, you can help me with my new projects and advise me what to create and improve there.

**Pull request merged**
